### ISSUE TITLE
typo in the table "Competenze per progettare servizi pubblici"

### ISSUE THREAD

**Issue by Clou-dia** [italia/manuale-operativo-design-docs#14]
Table of "Competenze per progettare servizi pubblici" has a small typo, UX Designer is repeated twice
https://github.com/italia/manuale-operativo-design-docs/blob/main/doc/gestione-del-progetto/le-competenze-per-progettare-servizi-pubblici.rst 

<img width="707" alt="Schermata 2022-05-24 alle 17 37 54" src="https://user-images.githubusercontent.com/98462345/170075963-b35809a6-068a-4d72-b90b-8720356591f8.png">

**Comment by danielaiozzo** [comment]
grazie @Clou-dia! @bfabio secondo te riusciamo ad eliminare il typo direttamente oppure mi consigli di ricreare la tabella per intero? (l'avevo fatta con tablegenerator...)
